<a href="https://colab.research.google.com/github/jaijypaul/ML-Project/blob/main/Iris_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
  def __init__(self,in_features=4,h1=8,h2=8,out_features=3):
    super().__init__()
    self.fc1=nn.Linear(in_features,h1)
    self.fc2=nn.Linear(h1,h2)
    self.out=nn.Linear(h2,out_features)

  def forward(self,x):
    x=F.relu(self.fc1(x))
    x=F.relu(self.fc2(x))
    x=self.out(x)

    return x

In [ ]:
torch.manual_seed(41)
model=Model()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
url='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df=pd.read_csv(url)
my_df.head()
my_df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [ ]:
my_df['variety']=my_df['variety'].replace('Setosa',0.0)
my_df['variety']=my_df['variety'].replace('Versicolor',1.0)
my_df['variety']=my_df['variety'].replace('Virginica',2.0)
my_df

/tmp/ipykernel_2237/540637692.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df['variety']=my_df['variety'].replace('Virginica',2.0)

     sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [ ]:
X= my_df.drop('variety',axis=1)
y=my_df['variety']
#convert these to numpy arrays
X=X.values
y=y.values

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X_train=torch.FloatTensor(X_train)
X_test=torch.FloatTensor(X_test)

y_train=torch.LongTensor(y_train)
y_test=torch.LongTensor(y_test)

In [ ]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [ ]:
epochs=200
losses=[]
for i in range (epochs):
  y_pred=model.forward(X_train)

  loss=criterion(y_pred,y_train)

  losses.append(loss)

  if i%10 ==0:
    print(f'Epoch:{i} and loss:{loss}')

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

Epoch:0 and loss:1.1428896188735962
Epoch:10 and loss:0.971087634563446
Epoch:20 and loss:0.6955528855323792
Epoch:30 and loss:0.41993448138237
Epoch:40 and loss:0.24405717849731445
Epoch:50 and loss:0.1396075189113617
Epoch:60 and loss:0.09179990738630295
Epoch:70 and loss:0.07232813537120819
Epoch:80 and loss:0.0631355568766594
Epoch:90 and loss:0.05770011246204376
Epoch:100 and loss:0.05383935198187828
Epoch:110 and loss:0.050785865634679794
Epoch:120 and loss:0.04823164641857147
Epoch:130 and loss:0.04602361470460892
Epoch:140 and loss:0.04408622160553932
Epoch:150 and loss:0.042358338832855225
Epoch:160 and loss:0.04080004245042801
Epoch:170 and loss:0.039382584393024445
Epoch:180 and loss:0.03808104991912842
Epoch:190 and loss:0.03687712177634239

In [ ]:
#plt.plot(range(epochs),losses)
#plt.ylabel("loss/error")
#plt.xlabel("epoch")

In [ ]:
with torch.no_grad():  #turn off back propag
  y_eval=model.forward(X_test)
  loss=criterion(y_eval,y_test)

In [ ]:
correct=0
with torch.no_grad():
  for i,data in enumerate(X_test):
    y_eval=model.forward(data)
    if y_test[i]==0:
      x="setosa"
    elif y_test[i]==1:
      x="Versicolor"
    else:
      x="Virginica"
    print(f'{i+1} {str(y_val)}  \t {y_test[i]}')

    if y_eval.argmax().item()==y_test[i]:
      correct+=1
print(f'we got  {correct} correct')

1 tensor([-12.9612,   0.4265,  10.2271])  	 2
2 tensor([-12.1121,  -0.0458,  10.2028])  	 2
3 tensor([  9.3854,   2.6774, -19.2038])  	 0
4 tensor([-5.4201,  3.8376, -1.4536])  	 1
5 tensor([-11.6462,   2.1990,   6.3706])  	 2
6 tensor([-10.7589,   0.8055,   7.8165])  	 2
7 tensor([-8.2922,  2.3276,  3.2935])  	 1
8 tensor([ 10.2512,   2.3351, -19.9683])  	 0
9 tensor([-12.2022,   0.3591,   9.6913])  	 2
10 tensor([-15.0822,  -0.3329,  13.0319])  	 2
11 tensor([-13.8590,   0.7637,  10.4854])  	 2
12 tensor([-4.6409,  3.7660, -2.0486])  	 1
13 tensor([ 10.3468,   2.6374, -20.5464])  	 0
14 tensor([ 10.1537,   2.5993, -20.1753])  	 0
15 tensor([-3.5949,  4.0015, -3.9646])  	 1
16 tensor([-3.8941,  3.9693, -3.4794])  	 1
17 tensor([-5.7795,  4.4591, -2.1433])  	 1
18 tensor([-7.8808,  2.9290,  2.0712])  	 2
19 tensor([  9.3092,   2.5813, -18.8911])  	 0
20 tensor([-4.2712,  4.0337, -3.0923])  	 1
21 tensor([  8.2478,   2.4531, -17.1222])  	 0
22 tensor([-6.9236,  3.2017,  0.8082])  	 1
23 tensor([-0.5478,  3.4126, -6.9386])  	 1
24 tensor([-5.1213,  4.2878, -2.4530])  	 1
25 tensor([-11.0394,   1.1571,   7.5351])  	 2
26 tensor([-5.7626,  3.8680, -1.2852])  	 1
27 tensor([-3.3605,  4.1125, -4.5412])  	 1
28 tensor([-7.8739,  3.1801,  1.6158])  	 1
29 tensor([-3.8756,  4.3035, -4.2381])  	 1
30 tensor([-12.1049,   0.4864,   9.3905])  	 2
we got  28 correct

In [ ]:
new_iris_data= torch.tensor([4.7,2.8,1.3,0.5])
with torch.no_grad():
  eval=model(new_iris_data)

  temp=eval.argmax().item()
  if temp==0:
      x="setosa"
  elif temp==1:
      x="Versicolor"
  else:
      x="Virginica"

  print(x)

setosa

In [ ]:
torch.save(model.state.dict(),'iris_data_model')

In [ ]:
new_model=Model()
new_model.load_state_dict(torch.load('iris_data_model'))